<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <ProjectReference Include="..\Admin.Contracts\Admin.Contracts.csproj" />
    <ProjectReference Include="..\Admin.Domain\Admin.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Files\Files.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <RootNamespace>Himapp.Admin.Application</RootNamespace>
  </PropertyGroup>
</Project>
