<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
	  <Compile Remove="Features\DailyLabor\Validators\**" />
	  <EmbeddedResource Remove="Features\DailyLabor\Validators\**" />
	  <None Remove="Features\DailyLabor\Validators\**" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.9" />
		<PackageReference Include="AWSSDK.S3" Version="4.0.102.2" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="ExcelDataReader" Version="3.7.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="7.0.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Npgsql" Version="8.0.0" />
		<ProjectReference Include="..\Execution.Contracts\Execution.Contracts.csproj" />
		<ProjectReference Include="..\Execution.Domain\Execution.Domain.csproj" />
		<ProjectReference Include="..\..\Admin\Admin.Contracts\Admin.Contracts.csproj" />
		<ProjectReference Include="..\..\..\Shared\Files\Files.csproj" />
	</ItemGroup>
	<PropertyGroup>
		<RootNamespace>Himapp.Execution.Application</RootNamespace>
	</PropertyGroup>
</Project>
