<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<ProjectReference Include="..\Execution.Contracts\Execution.Contracts.csproj" />
		<ProjectReference Include="..\Execution.Domain\Execution.Domain.csproj" />
		<ProjectReference Include="..\Execution.Infrastructure\Execution.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Shared\Workflow\Workflow.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Features\DailyLabor\Validators\" />
	</ItemGroup>
	<PropertyGroup>
		<RootNamespace>Himapp.Execution.Application</RootNamespace>
	</PropertyGroup>
</Project>
