// <auto-generated />
using System;
using Himapp.Execution.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himapp.Execution.Infrastructure.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    partial class ExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DDLSlipCode")
                        .HasColumnType("text");

                    b.Property<int?>("DPRSlipIssueID")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentContentType")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text");

                    b.Property<int?>("FinancialYearID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("IsDisapproved")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsNewParty")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<int?>("Mat")
                        .HasColumnType("integer");

                    b.Property<string>("NewParty")
                        .HasColumnType("text");

                    b.Property<int?>("PartyID")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("Skilled")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SlipDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SlipNumber")
                        .HasColumnType("integer");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint");

                    b.Property<int?>("TotalDPRManpower")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalWrkMins")
                        .HasColumnType("integer");

                    b.Property<int?>("UnSkilled")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("DailyDepartmentalLabourSlips");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlipDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ActivityCategoryID")
                        .HasColumnType("integer");

                    b.Property<string>("ActivityDetails")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DDLSlipID")
                        .HasColumnType("integer");

                    b.Property<int?>("DailyDepartmentalLabourSlipID")
                        .HasColumnType("integer");

                    b.Property<int?>("DebitPartyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLumSumWork")
                        .HasColumnType("boolean");

                    b.Property<int?>("LabourCategoryTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LunchHour")
                        .HasColumnType("numeric");

                    b.Property<int?>("NumOfLabour")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TOTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UOMID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.Property<int?>("WorkLocationID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WorkingHours")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("DailyDepartmentalLabourSlipID");

                    b.ToTable("DailyDepartmentalLabourSlipDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLabor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("ConstraintsAndReasons")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DLRCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DLRDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReportDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedActionPlan")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("RemoveMenPower")
                        .HasColumnType("boolean");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("DailyLabor", (string)null);
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLaborDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractorID")
                        .HasColumnType("integer");

                    b.Property<string>("ContractorName")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyLabourID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Mat")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductivityID")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Skilled")
                        .HasColumnType("integer");

                    b.Property<int?>("UnSkilled")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DailyLabourID");

                    b.ToTable("DailyLaborDetails", (string)null);
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HindranceAudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Hindrances")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextDayPlan")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DailyProgresses");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PlanQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Variance")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("DailyProgressDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Manpower", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SectionID")
                        .HasColumnType("integer");

                    b.Property<int>("StateID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Manpowers");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ManpowerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer");

                    b.Property<int>("ContractorID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManpowerID")
                        .HasColumnType("integer");

                    b.Property<int>("OtherCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkilledCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.Property<int>("UnskilledCount")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ManpowerID");

                    b.ToTable("ManpowerDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Planning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.PlanningDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlanningId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal>("TargetQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlanningDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ProjectActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProjectActivities");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.RateMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RateMasters");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HindranceAudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Hindrances")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextDayPlan")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int>("SectionID")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SiteDailyProgresses");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlipDetails", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", "DailyDepartmentalLabourSlip")
                        .WithMany("DailyDepartmentalLabourSlipDetails")
                        .HasForeignKey("DailyDepartmentalLabourSlipID");

                    b.Navigation("DailyDepartmentalLabourSlip");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLaborDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyLabor", "DailyLabor")
                        .WithMany("DailyLaborDetail")
                        .HasForeignKey("DailyLabourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLabor");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ManpowerDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.Manpower", "Manpower")
                        .WithMany("ManpowerDetail")
                        .HasForeignKey("ManpowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manpower");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", b =>
                {
                    b.Navigation("DailyDepartmentalLabourSlipDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLabor", b =>
                {
                    b.Navigation("DailyLaborDetail");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Manpower", b =>
                {
                    b.Navigation("ManpowerDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
