<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>Himapp.Safety.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Safety.Domain\Safety.Domain.csproj" />
	<ProjectReference Include="..\Safety.Contracts\Safety.Contracts.csproj" />
  </ItemGroup>

</Project>

