// <auto-generated />
using System;
using Himapp.Execution.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himapp.Execution.Infrastructure.Migrations.Execution
{
    [DbContext(typeof(ExecutionDbContext))]
    partial class ExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("execution")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OtherLabourRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("OutputRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RevenueRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkilledLabourRate")
                        .HasColumnType("numeric");

                    b.Property<int>("UOMID")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnSkilledLabourRate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Activities", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ActivityCategoryDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<int>("CategoryTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryTypeID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Name");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("Rate");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.ToTable("ActivityCategoryDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DDLSlipCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DDLSlipCode");

                    b.Property<int?>("DPRSlipIssueID")
                        .HasColumnType("integer")
                        .HasColumnName("DPRSlipIssueID");

                    b.Property<string>("DocumentContentType")
                        .HasColumnType("text")
                        .HasColumnName("DocumentContentType");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text")
                        .HasColumnName("DocumentName");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text")
                        .HasColumnName("DocumentPath");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int?>("IsDisapproved")
                        .HasColumnType("integer")
                        .HasColumnName("IsDisapproved");

                    b.Property<bool?>("IsNewParty")
                        .HasColumnType("boolean")
                        .HasColumnName("IsNewParty");

                    b.Property<string>("IssueNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("IssueNumber");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int?>("Mat")
                        .HasColumnType("integer")
                        .HasColumnName("Mat");

                    b.Property<string>("NewParty")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NewParty");

                    b.Property<int?>("PartyID")
                        .HasColumnType("integer")
                        .HasColumnName("PartyID");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<int?>("Skilled")
                        .HasColumnType("integer")
                        .HasColumnName("Skilled");

                    b.Property<DateTime?>("SlipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SlipDate");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint")
                        .HasColumnName("StateID");

                    b.Property<int?>("TotalDPRManpower")
                        .HasColumnType("integer")
                        .HasColumnName("TotalDPRManpower");

                    b.Property<int?>("TotalWrkMins")
                        .HasColumnType("integer")
                        .HasColumnName("TotalWrkMins");

                    b.Property<int?>("UnSkilled")
                        .HasColumnType("integer")
                        .HasColumnName("UnSkilled");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.ToTable("DailyDepartmentalLabourSlips", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlipDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ActivityDetails")
                        .HasColumnType("text")
                        .HasColumnName("ActivityDetails");

                    b.Property<int?>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<int?>("DDLSlipID")
                        .HasColumnType("integer")
                        .HasColumnName("DDLSlipID");

                    b.Property<int?>("DebitPartyID")
                        .HasColumnType("integer")
                        .HasColumnName("DebitPartyID");

                    b.Property<DateTime>("FromTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FromTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsLumSumWork")
                        .HasColumnType("boolean")
                        .HasColumnName("IsLumSumWork");

                    b.Property<int?>("LabourCategoryTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("LabourCategoryTypeID");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<decimal?>("LunchHour")
                        .HasColumnType("numeric")
                        .HasColumnName("LunchHour");

                    b.Property<int?>("NumOfLabour")
                        .HasColumnType("integer")
                        .HasColumnName("NumOfLabour");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("Quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint")
                        .HasColumnName("StateID");

                    b.Property<DateTime>("TOTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TOTime");

                    b.Property<int?>("UOMID")
                        .HasColumnType("integer")
                        .HasColumnName("UOMID");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.Property<int?>("WorkLocationID")
                        .HasColumnType("integer")
                        .HasColumnName("WorkLocationID");

                    b.Property<decimal?>("WorkingHours")
                        .HasColumnType("numeric")
                        .HasColumnName("WorkingHours");

                    b.HasKey("ID");

                    b.HasIndex("DDLSlipID");

                    b.ToTable("DailyDepartmentalLabourSlipDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLabor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("ConstraintsAndReasons")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DLRCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DLRDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ReportDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedActionPlan")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("RemoveMenPower")
                        .HasColumnType("boolean");

                    b.Property<short?>("StateID")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.HasIndex("DLRCode")
                        .IsUnique();

                    b.ToTable("DailyLabor", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLaborDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ActivityID")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractorID")
                        .HasColumnType("integer");

                    b.Property<string>("ContractorName")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyLabourID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Mat")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Skilled")
                        .HasColumnType("integer");

                    b.Property<int?>("UnSkilled")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DailyLabourID");

                    b.ToTable("DailyLaborDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DPRCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DPRCode");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("NextDayPlan")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("NextDayPlan");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("ReportDate");

                    b.Property<int>("StatusID")
                        .HasColumnType("integer")
                        .HasColumnName("StatusID");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("TotalAmount");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.ToTable("DailyProgress", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("Amount");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer")
                        .HasColumnName("DailyProgressID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<decimal?>("PlanQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("PlanQuantity");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("Rate");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<int?>("UOMID")
                        .HasColumnType("integer")
                        .HasColumnName("UOMID");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Variance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("Variance");

                    b.HasKey("ID");

                    b.HasIndex("DailyProgressID");

                    b.ToTable("DailyProgressDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressHindrance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("AudioUrl");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer")
                        .HasColumnName("DailyProgressID");

                    b.Property<string>("Hindrance")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Hindrance");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.HasIndex("DailyProgressID");

                    b.ToTable("DailyProgressHindrances", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Caption");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer")
                        .HasColumnName("DailyProgressID");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FileName");

                    b.Property<int?>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("FileSize");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FileType");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("PhotoUrl");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.HasIndex("DailyProgressID");

                    b.ToTable("DailyProgressPhotos", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ExecutionProjectConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxHours")
                        .HasColumnType("numeric");

                    b.Property<int>("MyProperty")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("ExecutionProjectConfigs", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Manpower", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("EntryDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<int>("SectionID")
                        .HasColumnType("integer")
                        .HasColumnName("SectionID");

                    b.Property<short>("StateID")
                        .HasColumnType("smallint")
                        .HasColumnName("StateID");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.ToTable("Manpowers", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ManpowerDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<int>("ContractorID")
                        .HasColumnType("integer")
                        .HasColumnName("ContractorID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsDepartment")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDepartment");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("ManpowerID")
                        .HasColumnType("integer")
                        .HasColumnName("ManpowerID");

                    b.Property<int>("OtherCount")
                        .HasColumnType("integer")
                        .HasColumnName("OtherCount");

                    b.Property<int>("SkilledCount")
                        .HasColumnType("integer")
                        .HasColumnName("SkilledCount");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("TotalCount");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.Property<int>("UnskilledCount")
                        .HasColumnType("integer")
                        .HasColumnName("UnskilledCount");

                    b.HasKey("ID");

                    b.HasIndex("ManpowerID");

                    b.ToTable("ManpowerDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Planning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AreaID")
                        .HasColumnType("integer")
                        .HasColumnName("AreaID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("PlanTypeID")
                        .HasColumnType("integer")
                        .HasColumnName("PlanTypeID");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("StartDate");

                    b.Property<int>("StatusID")
                        .HasColumnType("integer")
                        .HasColumnName("StatusID");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.ToTable("Plannings", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.PlanningDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<int>("AreaID")
                        .HasColumnType("integer")
                        .HasColumnName("AreaID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("PlanningID")
                        .HasColumnType("integer")
                        .HasColumnName("PlanningID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<decimal>("TargetQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("TargetQuantity");

                    b.Property<int>("UOMID")
                        .HasColumnType("integer")
                        .HasColumnName("UOMID");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.HasIndex("PlanningID");

                    b.ToTable("PlanningDetails", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.PlanningDocumentDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ContentType");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DocumentName");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FileExtension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("FilePath");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("PlanningID")
                        .HasColumnType("integer")
                        .HasColumnName("PlanningID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Remarks");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.HasIndex("PlanningID");

                    b.ToTable("PlanningDocumentDetail", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ProjectActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer")
                        .HasColumnName("ActivityID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("Enabled");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastModifiedDate");

                    b.Property<decimal>("OtherLabourRate")
                        .HasColumnType("numeric")
                        .HasColumnName("OtherLabourRate");

                    b.Property<bool>("OutputRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("OutputRequired");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer")
                        .HasColumnName("ProjectID");

                    b.Property<decimal>("RevenueRate")
                        .HasColumnType("numeric")
                        .HasColumnName("RevenueRate");

                    b.Property<decimal>("SkilledLabourRate")
                        .HasColumnType("numeric")
                        .HasColumnName("SkilledLabourRate");

                    b.Property<decimal>("UnSkilledLabourRate")
                        .HasColumnType("numeric")
                        .HasColumnName("UnSkilledLabourRate");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueID");

                    b.HasKey("ID");

                    b.ToTable("ProjectActivities", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NextDayPlan")
                        .HasColumnType("text");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.Property<int?>("SectionID")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("SiteDailyProgresses", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PlanQuantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("SiteDailyProgressID")
                        .HasColumnType("integer");

                    b.Property<int>("UOMID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Variance")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("SiteDailyProgressID");

                    b.ToTable("SiteDailyProgressDetail", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressHindrance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer");

                    b.Property<string>("Hindrance")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DailyProgressID");

                    b.ToTable("SiteDailyProgressHindrance", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyProgressID")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int?>("FileSize")
                        .HasColumnType("integer");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DailyProgressID");

                    b.ToTable("SiteDailyProgressPhoto", "execution");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlipDetails", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", "DailyDepartmentalLabourSlip")
                        .WithMany("DailyDepartmentalLabourSlipDetails")
                        .HasForeignKey("DDLSlipID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DailyDepartmentalLabourSlip");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLaborDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyLabor", "DailyLabor")
                        .WithMany("DailyLaborDetail")
                        .HasForeignKey("DailyLabourID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLabor");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyProgress", "DailyProgress")
                        .WithMany("DailyProgressDetail")
                        .HasForeignKey("DailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressHindrance", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyProgress", "DailyProgress")
                        .WithMany("DailyProgressHindrance")
                        .HasForeignKey("DailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgressPhoto", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.DailyProgress", "DailyProgress")
                        .WithMany("DailyProgressPhoto")
                        .HasForeignKey("DailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.ManpowerDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.Manpower", "Manpower")
                        .WithMany("ManpowerDetail")
                        .HasForeignKey("ManpowerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manpower");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.PlanningDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.Planning", "Planning")
                        .WithMany("PlanningDetail")
                        .HasForeignKey("PlanningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.PlanningDocumentDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.Planning", "Planning")
                        .WithMany("PlanningDocumentDetail")
                        .HasForeignKey("PlanningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressDetail", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.SiteDailyProgress", "DailyProgress")
                        .WithMany("SiteDailyProgressDetail")
                        .HasForeignKey("SiteDailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressHindrance", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.SiteDailyProgress", "DailyProgress")
                        .WithMany("SiteDailyProgressHindrance")
                        .HasForeignKey("DailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgressPhoto", b =>
                {
                    b.HasOne("Himapp.Execution.Domain.Entities.SiteDailyProgress", "DailyProgress")
                        .WithMany("SiteDailyProgressPhoto")
                        .HasForeignKey("DailyProgressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyProgress");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyDepartmentalLabourSlip", b =>
                {
                    b.Navigation("DailyDepartmentalLabourSlipDetails");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyLabor", b =>
                {
                    b.Navigation("DailyLaborDetail");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.DailyProgress", b =>
                {
                    b.Navigation("DailyProgressDetail");

                    b.Navigation("DailyProgressHindrance");

                    b.Navigation("DailyProgressPhoto");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Manpower", b =>
                {
                    b.Navigation("ManpowerDetail");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.Planning", b =>
                {
                    b.Navigation("PlanningDetail");

                    b.Navigation("PlanningDocumentDetail");
                });

            modelBuilder.Entity("Himapp.Execution.Domain.Entities.SiteDailyProgress", b =>
                {
                    b.Navigation("SiteDailyProgressDetail");

                    b.Navigation("SiteDailyProgressHindrance");

                    b.Navigation("SiteDailyProgressPhoto");
                });
#pragma warning restore 612, 618
        }
    }
}
