// <auto-generated />
using System;
using Himapp.Workflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himapp.Workflow.Infrastructure.Migrations.Workflow
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260812143457_InitialWorkflowMigration")]
    partial class InitialWorkflowMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ApprovalWorkflowCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovalWorkflowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinancialYearID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<byte?>("StateID")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("ApprovalWorkflow", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.ApprovalWorkflowRoleDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ApprovalWorkflowID")
                        .HasColumnType("integer");

                    b.Property<bool?>("CanAuthorize")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanUnAuthorize")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalWorkflowID");

                    b.ToTable("ApprovalWorkflowRoleDetails", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.ApprovalWorkflowRoleDetails", b =>
                {
                    b.HasOne("Himapp.Workflow.Domain.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("ApprovalWorkflowRoleDetails")
                        .HasForeignKey("ApprovalWorkflowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("ApprovalWorkflowRoleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
