// <auto-generated />
using System;
using Himapp.Workflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Himapp.Workflow.Infrastructure.Migrations.Workflow
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ApprovalWorkflowCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ApprovalWorkflowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.ToTable("CentralApprovalWorkflow", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflowProjectDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ApprovalWorkflowID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalWorkflowID");

                    b.ToTable("CentralApprovalWorkflowProjectDetails", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflowRoleDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ApprovalWorkflowID")
                        .HasColumnType("integer");

                    b.Property<bool?>("CanAuthorize")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanUnAuthorize")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.HasIndex("ApprovalWorkflowID");

                    b.ToTable("CentralApprovalWorkflowRoleDetails", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralUserRoleMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("ID");

                    b.ToTable("CentralUserRoleMapping", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralUserRoleMappingDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CentralRoleMappingID")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CentralRoleMappingID");

                    b.ToTable("CentralUserRoleMappingDetails", "public");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflowProjectDetails", b =>
                {
                    b.HasOne("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("ApprovalWorkflowProjectDetails")
                        .HasForeignKey("ApprovalWorkflowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflowRoleDetails", b =>
                {
                    b.HasOne("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("ApprovalWorkflowRoleDetails")
                        .HasForeignKey("ApprovalWorkflowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralUserRoleMappingDetails", b =>
                {
                    b.HasOne("Himapp.Workflow.Domain.Entities.CentralUserRoleMapping", "CentralUserRoleMapping")
                        .WithMany("Details")
                        .HasForeignKey("CentralRoleMappingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentralUserRoleMapping");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralApprovalWorkflow", b =>
                {
                    b.Navigation("ApprovalWorkflowProjectDetails");

                    b.Navigation("ApprovalWorkflowRoleDetails");
                });

            modelBuilder.Entity("Himapp.Workflow.Domain.Entities.CentralUserRoleMapping", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
