name: Dev Execution API Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore HiMapp_Monolithic.csproj

      - name: Build Project
        run: dotnet build HiMapp_Monolithic.csproj --configuration Release --no-restore

      - name: Publish Execution API
        run: dotnet publish HiMapp_Monolithic.csproj -c Release -o ./publish --no-restore

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: |
          ssh-keyscan -p ${{ secrets.SSH_PORT }} \
            -H ${{ secrets.SSH_DEV_HOST }} >> ~/.ssh/known_hosts

      - name: Upload Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "publish/*"
          target: "/home/ec2-user/HiMapp_Execution_API/publish/"

      - name: Restart Execution API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart HiMappExecutionAPI.service
            sudo systemctl status HiMappExecutionAPI.service --no-pager
